### ISSUE TITLE
访问域名失败

### ISSUE THREAD

**Issue by nexus181** [LyLme/lylme_spage#10]
我之前用docker部署网站，最后一步添加数据库显示没有权限，于是改成宝塔部署，添加数据库和创立站点后，访问域名却打不开

**Comment by LyLme** [comment]
宝塔默认页是否能打开，ping一下看看通断性

**Comment by nexus181** [comment]
> 宝塔默认页是否能打开，ping一下看看通断性
可以ping通，默认页打不开

**Comment by nexus181** [comment]
可以ping通，默认页打不开

**Comment by LyLme** [comment]
检查一下nginx环境，或者重新安装一下试试

**Comment by nexus181** [comment]
@LyLme 搜索引擎添加的图标没有显示，edge访问导航页图标没有毛玻璃效果，在谷歌和手机上有
![image](https://ei.aurora1.top/i/2023/04/12/uagl2w-0.webp)
![image]https://ei.aurora1.top/i/2023/04/11/zev7me-0.webp)
