### ISSUE TITLE
PS  * $site['PS']              链接描述 是不是用这个字段 本地添加的时候变样了

### ISSUE THREAD

**Issue by chenGit1763113879QQ** [LyLme/lylme_spage#14]
https://github.com/LyLme/lylme_spage/blob/31f42528e824662444259e73c3e03f05b2e09d53/site/index.php#L8

<img width="480" alt="图片" src="https://github.com/LyLme/lylme_spage/assets/20452996/03f8fe17-eb5a-498b-88cb-002a6f61b5a9">

**Comment by LyLme** [comment]
只是预留了字段，还没启用

**Comment by LyLme** [comment]
这个确实是个bug，后续计划修复
