### ISSUE TITLE
后台修改网站配置没有反应 无法修改

### ISSUE THREAD

**Issue by Rockney99** [LyLme/lylme_spage#15]
默认主题
刚开始搭建好可以正常修改不知道为什么现在修改无法修改

**Comment by LyLme** [comment]
请先尝试以下办法
- 更换浏览器
- 切换PHP版本5.6
- 关闭防火墙

**Comment by Rockney99** [comment]
Edge Chrome都试过了 没有用

**Comment by Rockney99** [comment]
测试了edge Chrome浏览器都不行 php8.0切换到5.6也不行 关闭防火墙指的是哪个

**Comment by Rockney99** [comment]
对了 我记得我原来是装的1.5.1版本然后更新到了1.6.1的

**Comment by LyLme** [comment]
重新安装试试吧
