### ISSUE TITLE
大佬，群晖安装出现一直保存数据库，过不去

### ISSUE THREAD

**Issue by wch19830910** [LyLme/lylme_spage#16]
群晖安装出现一直保存数据库，不知道什么原因
![搜狗截图20230626065000](https://github.com/LyLme/lylme_spage/assets/75171072/044c9c8a-dc2d-4953-b6d4-f08645ff40dc)
![搜狗截图20230626064947](https://github.com/LyLme/lylme_spage/assets/75171072/f871435d-7559-4115-b7f4-e88b9938a86c)

**Comment by LyLme** [comment]
转自六零导航页页交流2群
`@zzzzjjjffff 群晖web station-脚本语言设置-用户定义，选择编辑，把拓展名全打钩`

另外建议PHP版本选择5.6，本程序基于5.6开发，高版本可能存在未知问题

**Comment by wch19830910** [comment]
谢谢，已经按你的方法部署成功。非常感谢。好清新，功能强大。
