### ISSUE TITLE
上传logo报500，但是实际上传成功

### ISSUE THREAD

**Issue by zhlicen** [LyLme/lylme_spage#17]
![image](https://github.com/LyLme/lylme_spage/assets/3927021/8cd2f574-2041-44b8-910a-6f083729fc95)

![image](https://github.com/LyLme/lylme_spage/assets/3927021/9f1f5a77-7b54-4214-8c4b-d679a3200088)

**Comment by LyLme** [comment]
收到

**Comment by LyLme** [comment]
文件写入相关权限问题
设置网站根目录权限：`755`，用户：`www`，应用到子目录
