### ISSUE TITLE
通过docker成功安装后，后台首页呈现空白，其他功能正常

### ISSUE THREAD

**Issue by dodois** [LyLme/lylme_spage#18]
![image](https://github.com/LyLme/lylme_spage/assets/73285310/14ec6550-cff0-4f79-9098-bc7f358ee4bb)

**Comment by LyLme** [comment]
参考如下，看看是否能解决
[https://mp.weixin.qq.com/s/PumsL0zqFXuQzwB3IcVdEw](https://mp.weixin.qq.com/s/PumsL0zqFXuQzwB3IcVdEw)

**Comment by dodois** [comment]
没有找到相关的QA哦

**Comment by dodois** [comment]
![image](https://github.com/LyLme/lylme_spage/assets/73285310/e684bb88-c989-441b-b127-7e8bd74d485d)
请问 和这个有关系吗

**Comment by dodois** [comment]
建议将dockerfile中的 1000用户 改为 root用户

**Comment by LyLme** [comment]
> 建议将dockerfile中的 1000用户 改为 root用户
> 

抱歉，我不太了解docker，dockerfile由其他热心网友编写，如果您有更好的解决方案可以提交PR

**Comment by LyLme** [comment]
> ![image](https://github.com/LyLme/lylme_spage/assets/73285310/e684bb88-c989-441b-b127-7e8bd74d485d)
> 请问 和这个有关系吗

您可以注释`include/common.php`文件第7行，启用报错提示，反馈截图给我

**Comment by dodois** [comment]
![image](https://github.com/LyLme/lylme_spage/assets/73285310/bd421c3a-b1aa-4111-848c-2ea61f1854e0)
我以为是容器时区的问题，我去改了正确的时区，重启容器，问题依旧

**Comment by LyLme** [comment]
> ![image](https://github.com/LyLme/lylme_spage/assets/73285310/bd421c3a-b1aa-4111-848c-2ea61f1854e0)
> 我以为是容器时区的问题，我去改了正确的时区，重启容器，问题依旧

改php.ini的时区试试

**Comment by dodois** [comment]
好了 解决了，需要给admin目录和include目录 777权限
