### ISSUE TITLE
[Feature Request]希望能支持Docker部署

### ISSUE THREAD

**Issue by cmj2002** [LyLme/lylme_spage#2]
希望能支持Docker部署！

如果作者不熟悉Docker，希望告知需求的PHP和MySQL版本(以及其他可能的依赖)，我也可以自己写Dockerfile。

**Comment by LyLme** [comment]
PHP5.6就行，MySQL也是5.6，Docker不太了解，你可以试试

**Comment by cmj2002** [comment]
搞好了，把相关的 `Dockerfile`、`docker-compose.yml` 和教程放在了[网盘](https://onedrive.caomingjun.com/%F0%9F%96%A5%E8%BD%AF%E4%BB%B6/LyLme_spage%E7%9A%84Docker%E9%83%A8%E7%BD%B2/) ，欢迎大家去看看。

@LyLme 也可以把这个链接贴到 README 里

**Comment by nexus181** [comment]
> 搞好了，把相关的 `Dockerfile`、`docker-compose.yml` 和教程放在了[网盘](https://onedrive.caomingjun.com/%F0%9F%96%A5%E8%BD%AF%E4%BB%B6/LyLme_spage%E7%9A%84Docker%E9%83%A8%E7%BD%B2/) ，欢迎大家去看看。
> 
> @LyLme 也可以把这个链接贴到 README 里

大佬，docker部署后输入网址安装导航网页添加数据库时显示没有权限怎么回事啊？

**Comment by LyLme** [comment]
抱歉，不太熟悉docker
