### ISSUE TITLE
链接管理，获取按钮在开启和关闭error_reporting(0);时出现两种不同的情况

### ISSUE THREAD

**Issue by dodois** [LyLme/lylme_spage#21]
开启  error_reporting(0); 

![image](https://github.com/LyLme/lylme_spage/assets/73285310/b8f0e9a1-f67a-4ce5-9813-ddc9db27b509)

关闭  error_reporting(0);

![image](https://github.com/LyLme/lylme_spage/assets/73285310/62900391-68a8-45b0-a010-d85a677808a3)
关闭时，虽然提示获取成功，但是访问返回404 http://隐藏IP/files/download/20230714062949251.ico

**Comment by LyLme** [comment]
那就是没获取到，正常

**Comment by LyLme** [comment]
每个网站的代码结构都可能不同，图标获取失败很正常的
