### ISSUE TITLE
分组id在数据库能自动调节就好了

### ISSUE THREAD

**Issue by zzffking** [LyLme/lylme_spage#24]
不然修改或添加分组，调节位置只是在前台调节，在后台链接管理里面，点击会默认跳转到在数据库id为1的那个分组
还有就是有密码那里 要是有个token放在url中 替换掉登录这个步骤就更完美了。 当然只是建议。这样不用输入密码了，放在自己收藏夹里点进去比较方便。

**Comment by LyLme** [comment]
分组id是在数据表中是主键，Token这个简单，可以自行实现，把admin/login.php文件中的判断账号密码是否正确替换成get获取token参数即可，你稍微懂点代码就能自行修改

**Comment by LyLme** [comment]
id那个可以用sort字段排序

**Comment by zzffking** [comment]
> id那个可以用sort字段排序

ok 谢谢解答 我就动手改改 毕竟满足的只是我一个人的要求 哈哈哈
