### ISSUE TITLE
自动部署失败

### ISSUE THREAD

**Issue by dfbb9216** [LyLme/lylme_spage#25]
设置完端口号后，提示

正在下载Docker镜像...
Error response from daemon: Head "https://registry-1.docker.io/v2/caomingjun/navpage/manifests/latest": dial tcp: lookup registry-1.docker.io on [::1]:53: server misbehaving
终止

**Comment by LyLme** [comment]
建议使用常规方式安装，Docker脚本为网友编写，本人也不懂Docker
