### ISSUE TITLE
主页 随机一言 会全部展示data.dat文档内容

### ISSUE THREAD

**Issue by FTM9664** [LyLme/lylme_spage#26]
如图，新版1.7.0的首页会显示所有data.dat文档内容
![image](https://github.com/LyLme/lylme_spage/assets/109845824/e67208cb-1ffd-4438-8f00-b92621cddbc5)

**Comment by LyLme** [comment]
windows系统上可能会出现这个问题，开发的时候没测试过win系统，linux更换5.6版本php试试
