### ISSUE TITLE
部署以后后台首页不显示，且无法点击用户名相关部分

### ISSUE THREAD

**Issue by awhao** [LyLme/lylme_spage#28]
![图片](https://github.com/LyLme/lylme_spage/assets/37777108/46dfb39e-b0cf-4e96-baeb-dca42f99b645)
docker-compose文件如下
![图片](https://github.com/LyLme/lylme_spage/assets/37777108/a0fe5174-7a49-43cb-a6be-c92b7776a52b)

采用了本地nginx代理，代码如下
![图片](https://github.com/LyLme/lylme_spage/assets/37777108/c121549b-ad51-4075-ae50-cbae5519106d)
![图片](https://github.com/LyLme/lylme_spage/assets/37777108/6cf22a76-4041-4f1e-8ac1-2a5513a10b7c)
![图片](https://github.com/LyLme/lylme_spage/assets/37777108/54fc5948-5bab-42a0-96f5-dac5fba56c37)
![图片](https://github.com/LyLme/lylme_spage/assets/37777108/8f43f0b0-a0a7-439e-9b46-2e0aed6bfd47)

**Comment by LyLme** [comment]
估计是docker的PHP环境的问题，docker部署我不太清楚
