### ISSUE TITLE
请问需要有哪些php扩展呢？

### ISSUE THREAD

**Issue by eureka6** [LyLme/lylme_spage#30]
输入数据库信息后，点下一步，一直卡在了do=3，进度条只有一半。
看以前的issues，好像是php扩展没装？

第一页的php扩展要求也全符合了。

**Comment by eureka6** [comment]
https://demo.files.gallery/index.php?check=1

有没有上面这种自己排查的办法呢？

麻烦大佬了~

**Comment by LyLme** [comment]
这个应该是mysqli扩展没装导致的

**Comment by eureka6** [comment]
先祝大佬节日快乐~

我的腾讯云服务器因为各种问题一直搞不好。只有用docker部署成功过，然而呢，我想在容器外用nginx反代的时候，经常会跳转到【域名：端口】这种地址，而浏览器似乎只会访问【域名】，这就导致一些后台需要手动给域名后面加上端口才可以顺利访问。

请问这是nginx配置的问题吗？我看容器里好像有已经有一个nginx了

**Comment by ChrisStudyH** [comment]
我也遇到这个问题，尝试修改了php版本就可以了，（php8.1-->php8.0）
![Snipaste_2023-10-03_18-06-29](https://github.com/LyLme/lylme_spage/assets/67332633/e94a4bc4-e782-4129-bfc5-5c80c6b46da6)
![Snipaste_2023-10-03_18-07-05](https://github.com/LyLme/lylme_spage/assets/67332633/e28ae9fa-c20a-4080-bad6-b4d11293556a)

**Comment by eureka6** [comment]
已解决，通过降低php版本为5.6，另外，还需要安装好php-gd扩展，这样在申请收录的界面才会出现验证码图片。
