### ISSUE TITLE
有一个小BUG， 搜索引擎BUG

### ISSUE THREAD

**Issue by aoxijy** [LyLme/lylme_spage#40]
修改谷歌为第一搜索引擎后 ，图标会默认为百度图标，切换其他搜索再切换回来，谷歌图标就消失了。希望能修复，最喜欢的导航，没有之一了

**Comment by LyLme** [comment]
哪个主题？

**Comment by aoxijy** [comment]
在用LyLme主题，图标不显示是尺寸问题， 已经解决，但是设置谷歌为第一搜索，默认搜索图标为百度，从新部署过，也是一样的，不会切换到谷歌的搜索图标，请大佬看看

**Comment by LyLme** [comment]
默认搜索是百度写死在主题代码里面了，后续修复这个问题，你也可以在主题文件搜索百度关键词替换图标，名称，和url

**Comment by aoxijy** [comment]
好的，谢谢，这个导航是真的棒，特别是你的主题，用的舒服😄
