### ISSUE TITLE
一直卡在保存数据库那里！

### ISSUE THREAD

**Issue by renshinizhenhao** [LyLme/lylme_spage#41]
也没有任何提示、
![Snipaste_2023-11-28_14-19-59](https://github.com/LyLme/lylme_spage/assets/103295435/eac7a7a9-c202-47e8-8b66-006675fba1d1)

**Comment by renshinizhenhao** [comment]
> > 这是因为php环境不支持mysqli扩展
> 
> [问题#27](https://github.com/LyLme/lylme_spage/issues/27)

php添加了mysqli扩展又卡这里了
![Snipaste_2023-11-28_16-38-06](https://github.com/LyLme/lylme_spage/assets/103295435/5224629d-adf4-482f-9547-21b098f8494c)

**Comment by LyLme** [comment]
php版本换5.6试试
