### ISSUE TITLE
申请收录验证码不显示啊。

### ISSUE THREAD

**Issue by renshinizhenhao** [LyLme/lylme_spage#42]
![Snipaste_2023-11-28_18-10-13](https://github.com/LyLme/lylme_spage/assets/103295435/37701b88-e1c0-40a7-a4a9-7c2bd72ebc27)

**Comment by LyLme** [comment]
GD库扩展未安装，另外建议使用编译好的PHP版本搭建，看你这个情况解决了这个问题估计还会遇到一些因为扩展缺少导致的问题

**Comment by LyLme** [comment]
版本安装的环境检测那个只是摆设，它不包含一些常用的函数或者扩展检测，不建议使用docker方式部署，因为PHP环境配置比较复杂

**Comment by LyLme** [comment]
README的docker脚本为网友编写，未经过严格测试，可能存在BUG

**Comment by renshinizhenhao** [comment]
> 版本安装的环境检测那个只是摆设，它不包含一些常用的函数或者扩展检测，不建议使用docker方式部署，因为PHP环境配置比较复杂

我用1panel构建的php部署方式，就一直卡在数据库那里。没有办法了。咱也不知道PHP构建需要什么扩展。我才选择了docker部署的。我目前就发现了这个验证码不显示。其他都还好。也就无所谓了

**Comment by LyLme** [comment]
我不太懂doxker
