### ISSUE TITLE
背景能不能设置固定？

### ISSUE THREAD

**Issue by renshinizhenhao** [LyLme/lylme_spage#43]
然后把分组的框在弄成可以调节透明度的！

**Comment by renshinizhenhao** [comment]
谷歌搜什么关键字> 你可以通过css实现，在后台设置>自定义footer，添加css代码，具体代码可以google或者询问chatGPT

**Comment by LyLme** [comment]
您可以在`后台设置->网站配置->自定义footer`添加如下代码来实现背景固定
```html
<style>
.bottom-cover {
    background-image: none !important; /*取消遮罩*/
}
.banner-video > img:first-child {
    position: fixed !important;  /*固定背景图片*/
}
</style>
```

**Comment by renshinizhenhao** [comment]
> 您可以在`后台设置->网站配置->自定义footer`添加如下代码来实现背景固定
> 
> ```
> <style>
> .bottom-cover {
>     background-image: none !important; /*取消遮罩*/
> }
> .banner-video > img:first-child {
>     position: fixed !important;  /*固定背景图片*/
> }
> </style>
> ```

谢谢大佬的帮助。非常漂亮！遮罩能不能设置透明度，而不是取消。

**Comment by LyLme** [comment]
晚上有空我再看看

**Comment by renshinizhenhao** [comment]
> 晚上有空我再看看

大佬，结果如何？
