### ISSUE TITLE
从老版本升级到新版本的教程

### ISSUE THREAD

**Issue by lerogo** [LyLme/lylme_spage#50]
从老版本升级到新版本的教程

**Comment by LyLme** [comment]
如果后台不能更新可以去release下载update.zip结尾的更新压缩包，直接上传根目录解压就行，数据库文件会自动升级

**Comment by dongbeixiaohuo** [comment]
按照以上方法更新后，访问web页面报错，“
Catchable fatal error: Argument 1 passed to setIsNext() must be an instance of bool, boolean given, called in /var/www/html/install/index.php on line 235 and defined in /var/www/html/install/index.php on line 313”
