### ISSUE TITLE
GD是什么？安装的时候提示不支持

### ISSUE THREAD

**Issue by MemoryCollection** [LyLme/lylme_spage#53]
11111111111111

**Comment by LyLme** [comment]
GD是PHP生成图像的扩展库，本项目用于生成验证码图片。如果提示不支持可以尝试切换PHP版本，这个扩展一般都是包含的，如果您的PHP环境是自行编译的，可以参考[如何让 php 加载 GD？ - 知乎](https://www.zhihu.com/question/588126437)
