### ISSUE TITLE
请问您的导航页下方的今日资讯是怎么实现或设置的呀，好喜欢

### ISSUE THREAD

**Issue by btrencai** [LyLme/lylme_spage#56]
![e1b973f47cc7a4f39c57cc4aadf6c94](https://github.com/LyLme/lylme_spage/assets/88539735/5cc2427c-6e2e-4bcb-80a3-8c2400b65919)

**Comment by LyLme** [comment]
[https://lytoday.lylme.com/code.html](https://lytoday.lylme.com/code.html)
