### ISSUE TITLE
天气切换城市部分县城无法切换

### ISSUE THREAD

**Issue by SliverKeigo** [LyLme/lylme_spage#57]
![recording](https://github.com/LyLme/lylme_spage/assets/112426853/1c96e6f0-6542-4c1f-a3c6-27f9160a7277)
当选择的城市超出天气展示区后，城市无法选中，下拉框已经无法拖动，所以无法移动到展示区选中城市
复现步骤：切换城市时，选择任意不在天气展示区内的城市

**Comment by LyLme** [comment]
第三方天气插件BUG，无法修复，只能当做装饰品或者找其它方式替代
