### ISSUE TITLE
建议增加链接备注

### ISSUE THREAD

**Issue by ma3252788** [LyLme/lylme_spage#59]
比如这种:

<img width="1427" alt="image" src="https://github.com/LyLme/lylme_spage/assets/22229456/8593f8fa-0623-40d5-8b6a-eae007ea0051">

或者鼠标放上之后对链接进行介绍，感觉这样更加实用些~

**Comment by LyLme** [comment]
目前后台还不支持链接描述的设置，请期待后续更新
