### ISSUE TITLE
新增链接失败 

### ISSUE THREAD

**Issue by SliverKeigo** [LyLme/lylme_spage#61]
![recording](https://github.com/LyLme/lylme_spage/assets/112426853/7a13e6f3-0897-4c0d-b3cd-f8875e21f2a6)
![image](https://github.com/LyLme/lylme_spage/assets/112426853/3e5dfe13-b27e-4d4a-947d-90fa3ea5c822)

**Comment by SliverKeigo** [comment]
> 之前更新过1.8.0吗

![image](https://github.com/LyLme/lylme_spage/assets/112426853/652f051d-3d63-4b78-ad7d-17178a4f8bbf)
我检查一下是不是我mysql问题 目前除了新增链接 其他都没有问题

**Comment by SliverKeigo** [comment]
> 之前更新过1.8.0吗

应该是我mysql问题

**Comment by SliverKeigo** [comment]
![image](https://github.com/LyLme/lylme_spage/assets/112426853/8d08556c-2dae-4938-9eab-e0fe7357de2c)
我想确认一下最初的链接的数据是存放在数据库里的吗

**Comment by LyLme** [comment]
对，你可以截图一下lylme_link表结构给我看看

**Comment by SliverKeigo** [comment]
> 对，你可以截图一下lylme_link表结构给我看看

那么删除是没有问题的，也就是说可能问题不在我数据库

**Comment by SliverKeigo** [comment]
> 对，你可以截图一下lylme_link表结构给我看看

![image](https://github.com/LyLme/lylme_spage/assets/112426853/8be137cf-3013-441b-a689-a276a84eabd3)

**Comment by SliverKeigo** [comment]
> 对，你可以截图一下lylme_link表结构给我看看

![image](https://github.com/LyLme/lylme_spage/assets/112426853/3361f04f-9f62-4a21-a2e8-8c8abfea8443)
在这

**Comment by LyLme** [comment]
给ID添加一个主键和自增

**Comment by LyLme** [comment]
- ![Image_1707063549899.jpg](https://github.com/LyLme/lylme_spage/assets/88341678/27e94c32-4403-4b9e-a56a-26e518756c6e)

**Comment by hanxi** [comment]
@LyLme 可以考虑把这两行加入到 update.sql 里。
```sql
alter table lylme_links add primary key (id);
alter table lylme_links change id id int(4) NOT NULL AUTO_INCREMENT COMMENT '链接ID';
```
