### ISSUE TITLE
一键docker部署成功之后遇到的问题

### ISSUE THREAD

**Issue by renshinizhenhao** [LyLme/lylme_spage#64]
一键docker部署成功之后遇我创建分组和添加链接均未能成功。不知道是何原因，求解答。

![Snipaste_2024-02-28_20-19-59](https://github.com/LyLme/lylme_spage/assets/103295435/7f7834ca-4dd6-4cf7-8753-e3ef36f2955c)
![Snipaste_2024-02-28_20-20-30](https://github.com/LyLme/lylme_spage/assets/103295435/d75c42ce-4956-4665-9766-8e339f5b2f9c)
![Snipaste_2024-02-28_20-21-08](https://github.com/LyLme/lylme_spage/assets/103295435/750d9124-8b57-4b4c-82cd-3427b3c37c53)

**Comment by LyLme** [comment]
可能是1.8导致的bug，如果没有重要数据可以尝试更新到最新版本后删除install/install.lock文件，然后重新安装
。或者检查改表的主键是否存在，因为1.8的bug导致数据表出现问题

**Comment by renshinizhenhao** [comment]
那我就等后面的优化的docker部署了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月6日(周三) 上午8:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [LyLme/lylme_spage] 一键docker部署成功之后遇到的问题 (Issue #64)




 
可能是1.8导致的bug，如果没有重要数据可以尝试更新到最新版本后删除install/install.lock文件，然后重新安装
 。或者检查改表的主键是否存在，因为1.8的bug导致数据表出现问题
