### ISSUE TITLE
无法增加管理组的问题

### ISSUE THREAD

**Issue by chenzhelong** [LyLme/lylme_spage#67]
![1709627048074](https://github.com/LyLme/lylme_spage/assets/34223728/5e96b7eb-a4e2-491a-a721-029d9c0ffd3a)

![fe9de95410325a2f7ed3c7151459239](https://github.com/LyLme/lylme_spage/assets/34223728/e88e861e-1fe5-4471-b754-d189fc0a390e)

给非空字段传了空值~~~
@LyLme 兄弟你来改吧

**Comment by LyLme** [comment]
收到

**Comment by LyLme** [comment]
这个就是这样，就是传空值，主键会自增
