### ISSUE TITLE
http://域名/install安装出错

### ISSUE THREAD

**Issue by tmyovo** [LyLme/lylme_spage#7]
使用http://abc/install安装会弹出"下载"这个文件名的下载文件   版本1.3 
![image](https://user-images.githubusercontent.com/101644740/201021203-dce1f691-f09a-44f6-b023-6863fab3117f.png)
![image](https://user-images.githubusercontent.com/101644740/201021301-64dfe17c-5ed7-4f8c-a44d-33e2ac82c952.png)

**Comment by LyLme** [comment]
切换PHP版本为5.6试试
