### ISSUE TITLE
为啥后台首页不显示，是空白的，其他部分都是好的

### ISSUE THREAD

**Issue by RebellionAQG** [LyLme/lylme_spage#71]
为啥后台首页不显示，是空白的，其他部分都是好的
![QQ截图20240402144856](https://github.com/LyLme/lylme_spage/assets/126437353/98660908-73a3-42c6-8dbe-1c0eb319755d)
![Snipaste_2024-04-02_14-49-57](https://github.com/LyLme/lylme_spage/assets/126437353/931782b1-6bb2-4294-a1e0-3218713ce9d9)

是哪个文件出问题了吗？

**Comment by LyLme** [comment]
注释`include/common.php`文件第7行的禁用报错信息，看看报错内容
