### ISSUE TITLE
可以支持Webhook动态变更地址么

### ISSUE THREAD

**Issue by caiwenmin** [LyLme/lylme_spage#76]
希望后台可以提供一个接口，可以自定义url路径，通过请求这个接口可以变更某个导航地址的访问路径

**Comment by LyLme** [comment]
可以编辑`function.php`文件，rearr函数自行添加

**Comment by caiwenmin** [comment]
> 可以编辑`function.php`文件，后面函数自行添加

需要的是一个对外的接口，我可以通过http请求访问这个接口，实现对某一个导航地址的动态变更

**Comment by LyLme** [comment]
近期暂无计划
