### ISSUE TITLE
docker部署添加链接失败

### ISSUE THREAD

**Issue by ycllwl** [LyLme/lylme_spage#77]
添加链接失败！
删除链接正常

**Comment by suqir** [comment]
> 添加链接失败！ 删除链接正常

install时的建表sql文件有误，没有设置主键以及id自增，导致后面插入的时候不能给id插入NULL。你可以进入mysql容器，修改lylme_link表：添加id为主键`alter table lylme_links add primary key(id);`，然后把id设为自增`alter table lylme_links modify id int auto_increment;`

**Comment by LyLme** [comment]
确实是主键的问题，后续修复
