### ISSUE TITLE
导航跳转“/***”时，nginx会删除端口号默认80，导致无法访问

### ISSUE THREAD

**Issue by TrisAXJ** [LyLme/lylme_spage#80]
docker部署时nginx宿主机8095:80，访问localhost:8095
导航跳转“/***”时，nginx会删除端口号8095默认80，导致无法访问

**Comment by TrisAXJ** [comment]
在nginx配置default.conf中内网访问server下也加上absolute_redirect off;

**Comment by LyLme** [comment]
好的，感谢贡献
