### ISSUE TITLE
添加数据库后一直要写入权限怎么回事？root用户home目录下还能没权限

### ISSUE THREAD

**Issue by nexus181** [LyLme/lylme_spage#9]

**Comment by LyLme** [comment]
尝试为www用户，权限755，应用到子目录试试

**Comment by Rockney99** [comment]
> 

唉 我宝塔搭不了 用docker部署填写完数据库也是这样 root www 都不行

**Comment by Rockney99** [comment]
> > 
> 
> 唉 我宝塔搭不了 用docker部署填写完数据库也是这样 root www 都不行

![image](https://github.com/LyLme/lylme_spage/assets/42824224/57dc3b3b-4c59-46af-bac1-7383faf7f30d)
